# Generated by Django 4.0.4 on 2022-05-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_status_report_at',
            field=models.TimeField(blank=True, null=True, verbose_name='send status report at'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_report_last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='status report last sent at'),
        ),
    ]
