# Generated by Django 4.0.4 on 2022-05-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user_send_status_report_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_report_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], default='en', max_length=2, verbose_name='Status report language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='send_status_report_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Send status report at (UTC)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_report_last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Status report last sent at'),
        ),
    ]
