# Generated by Django 4.0.4 on 2022-05-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_user_status_report_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='send_status_report_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Send status report at'),
        ),
    ]
