# Generated by Django 4.0.2 on 2022-02-04 15:12

from django.db import migrations, models
import django.db.models.deletion
import inventory.models
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=inventory.models.object_image_upload_handler, verbose_name='image')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'alert'), (20, 'warning'), (30, 'normal')], default=30, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_object', to='inventory.object', verbose_name='object')),
            ],
            options={
                'verbose_name': 'sensor',
                'verbose_name_plural': 'sensors',
                'ordering': ['status', 'name'],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
