# Generated by Django 4.0.4 on 2022-05-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['owner', 'management_group', 'maintenance_group'], name='inventory_l_owner_i_3fe214_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['owner', 'management_group', 'maintenance_group'], name='inventory_o_owner_i_653cc5_idx'),
        ),
    ]
