# Generated by Django 4.0.4 on 2022-05-28 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0002_location_inventory_l_owner_i_3fe214_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['status', 'name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['status', 'name'], 'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['status', 'name'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.location_image_upload_handler, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='maintenance_group',
            field=models.ForeignKey(blank=True, help_text='Group members can view this location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_maintenance_group', to='auth.group', verbose_name='Maintenance group'),
        ),
        migrations.AlterField(
            model_name='location',
            name='management_group',
            field=models.ForeignKey(blank=True, help_text='Group members can view, change or delete this location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_management_group', to='auth.group', verbose_name='Management group'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(help_text='Owner can view, change or delete this location.', on_delete=django.db.models.deletion.CASCADE, related_name='location_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Alert'), (20, 'Warning'), (30, 'Normal')], default=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='object',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.object_image_upload_handler, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='object',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_location', to='inventory.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='object',
            name='maintenance_group',
            field=models.ForeignKey(blank=True, help_text='Group members can view this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_maintenance_group', to='auth.group', verbose_name='Maintenance group'),
        ),
        migrations.AlterField(
            model_name='object',
            name='management_group',
            field=models.ForeignKey(blank=True, help_text='Group members can view or update this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_management_group', to='auth.group', verbose_name='Management group'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(help_text='Owner can view, change or delete this object.', on_delete=django.db.models.deletion.CASCADE, related_name='object_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='object',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Alert'), (20, 'Warning'), (30, 'Normal')], default=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='object',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.object_image_upload_handler, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_object', to='inventory.object', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Alert'), (20, 'Warning'), (30, 'Normal')], default=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='webhook_authorization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Webhook authorization'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='webhook_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Webhook payload'),
        ),
    ]
