# Generated by Django 4.0.2 on 2022-02-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='payload',
            field=models.JSONField(blank=True, null=True, verbose_name='payload'),
        ),
    ]
