# Generated by Django 4.0.2 on 2022-02-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_sensor_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='payload',
        ),
        migrations.AddField(
            model_name='sensor',
            name='webhook_authorization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='webhook authorization'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='webhook_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='webhook payload'),
        ),
    ]
