# Generated by Django 4.0.1 on 2022-01-20 15:26

from django.db import migrations, models
import django.db.models.deletion
import maintenance.models
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Overdue'), (20, 'Due'), (30, 'Pending'), (40, 'Inactive')], default=30, verbose_name='status')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='due at')),
                ('overdue_at', models.DateTimeField(blank=True, null=True, verbose_name='overdue at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_object', to='inventory.object', verbose_name='object')),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'work',
                'ordering': ['status', 'overdue_at', 'due_at', 'updated_at'],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('image', models.ImageField(blank=True, null=True, upload_to=maintenance.models.log_image_upload_handler, verbose_name='image')),
                ('labor_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='labor costs')),
                ('material_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='material costs')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_object', to='inventory.object', verbose_name='object')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_work', to='maintenance.work', verbose_name='work')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
