# Generated by Django 4.0.1 on 2022-01-18 11:43

from django.db import migrations, models
import django.db.models.deletion
import maintenance.models
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Overdue'), (20, 'Due'), (30, 'Pending'), (40, 'Inactive')], default=30)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_objekt', to='inventory.objekt')),
            ],
            options={
                'ordering': ['status', 'overdue_at', 'due_at', 'updated_at'],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=maintenance.models.log_image_upload_handler)),
                ('labor_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_journal', to='maintenance.work')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
