# Generated by Django 4.0.2 on 2022-02-20 17:35

from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_sensor_payload_sensor_webhook_authorization_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonpath_expression', models.CharField(max_length=255, verbose_name='JSONpath expression')),
                ('condition', models.CharField(choices=[('==', 'equals'), ('!=', 'not equals'), ('<', 'less than'), ('<=', 'less than or equal to'), ('>', 'greater than'), ('>=', 'greater than or equal to')], max_length=2, verbose_name='condition')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('action', models.CharField(choices=[(10, 'alert'), (20, 'warning'), (30, 'normal')], max_length=9, verbose_name='action')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_sensor', to='inventory.sensor', verbose_name='sensor')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
