# Generated by Django 4.0.2 on 2022-02-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='name',
            field=models.CharField(default='test', max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trigger',
            name='action',
            field=models.CharField(choices=[('sensor10', 'Set sensor status to green'), ('sensor20', 'Set sensor status to amber'), ('sensor30', 'Set sensor status to red')], max_length=9, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='jsonpath_expression',
            field=models.CharField(max_length=200, verbose_name='JSONpath expression'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='value',
            field=models.CharField(max_length=200, verbose_name='value'),
        ),
    ]
