# Generated by Django 4.0.4 on 2022-05-28 08:13

from django.db import migrations, models
import django.db.models.deletion
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_location_options_alter_object_options_and_more'),
        ('maintenance', '0002_alter_journal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'overdue_at', 'due_at', 'updated_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='sensor_status',
        ),
        migrations.AddField(
            model_name='trigger',
            name='amber_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Warning value'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='red_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alert value'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Alert'), (20, 'Warning'), (30, 'Normal')], default=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=maintenance.models.journal_image_upload_handler, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='labor_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Labor costs'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='material_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Material costs'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_object', to='inventory.object', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_task', to='maintenance.task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_object', to='inventory.object', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='task',
            name='overdue_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Overdue at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Overdue'), (20, 'Due'), (30, 'Pending'), (40, 'Inactive')], default=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='condition',
            field=models.CharField(choices=[('==', 'equals'), ('!=', 'not equals'), ('<', 'less than'), ('<=', 'less than or equal to'), ('>', 'greater than'), ('>=', 'greater than or equal to')], max_length=2, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_sensor', to='inventory.sensor', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='value',
            field=models.CharField(max_length=200, verbose_name='Value'),
        ),
    ]
