# Generated by Django 4.0.4 on 2022-05-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_task_options_remove_trigger_sensor_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='value',
        ),
        migrations.AddField(
            model_name='trigger',
            name='sensor_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sensor alue'),
        ),
    ]
