# Generated by Django 4.0.3 on 2022-03-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_trigger_name_alter_trigger_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='action',
        ),
        migrations.AddField(
            model_name='trigger',
            name='sensor_status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'alert'), (20, 'warning'), (30, 'normal')], default=10, verbose_name='sensor status'),
            preserve_default=False,
        ),
    ]
